# site settings
title: Jonathan Eaton
subtitle: Cultural Anthropologist
email: jonathan.eaton@ubc.ca
description: I study the relationship between heritage and disaster recovery planning to help people preserve what they value in the face of uncertain futures.
baseurl: # the subpath of your site, e.g. /blog
url: https://eaton-j.github.io # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code:
country: Canada and USA
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  google: https://scholar.google.com/citations?user=5SjIWHYAAAAJ&hl=en
  Instagram:
  LinkedIn: https://www.linkedin.com/in/jonathan-e-30805322/
  Twitter: 
  Facebook:
  Slack:
  fa-ORCID: https://orcid.org/0000-0001-8681-4707

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
